const CACHE='optical-ray-lab-v3';
const ASSETS=['./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png','./apple-touch-icon.png'];
const OLD1="S={o:{x:-40,h:15,dir:'right'},n:21,grid:false,e:[]}";
const NEW1="S={o:{x:-30,h:10,dir:'right'},n:21,grid:false,e:[]}";
const OLD2="function standard(){S.o={x:-40,h:15,dir:'right'};S.e=[];add('convexLens',5,24,44);add('concaveMirror',62,28,48,'left');sync()}";
const NEW2="function standard(){S.o={x:-30,h:10,dir:'right'};S.e=[];add('convexLens',0,12,80);add('concaveLens',12,10,80);sync()}";
const OLD3="function optic(e){let x=sx(e.x),yt=sy(e.a/2),yb=sy(-e.a/2);ctx.save();ctx.lineWidth=3;ctx.strokeStyle=mirror(e.type)?'#6b6f78':'#2764a8';if(mirror(e.type)){ctx.beginPath();ctx.moveTo(x,yt);ctx.lineTo(x,yb);ctx.stroke();for(let y=yt;y<yb;y+=10){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(e.face==='left'?7:-7),y+5);ctx.stroke()}}else{ctx.fillStyle='#7dc8f033';ctx.beginPath();ctx.moveTo(x,yt);ctx.quadraticCurveTo(x+(e.type==='convexLens'?10:-7),sy(0),x,yb);ctx.quadraticCurveTo(x+(e.type==='convexLens'?-10:7),sy(0),x,yt);ctx.fill();ctx.stroke()}ctx.restore()}";
const NEW3="function optic(e){let x=sx(e.x),yt=sy(e.a/2),yb=sy(-e.a/2),ym=sy(0);ctx.save();ctx.lineWidth=3;ctx.strokeStyle=mirror(e.type)?'#6b6f78':'#2764a8';if(mirror(e.type)){ctx.beginPath();ctx.moveTo(x,yt);ctx.lineTo(x,yb);ctx.stroke();for(let y=yt;y<yb;y+=10){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(e.face==='left'?7:-7),y+5);ctx.stroke()}}else{ctx.fillStyle='#7dc8f033';ctx.beginPath();if(e.type==='convexLens'){ctx.moveTo(x-2,yt);ctx.quadraticCurveTo(x-11,ym,x-2,yb);ctx.lineTo(x+2,yb);ctx.quadraticCurveTo(x+11,ym,x+2,yt)}else{ctx.moveTo(x-10,yt);ctx.quadraticCurveTo(x-3,ym,x-10,yb);ctx.lineTo(x+10,yb);ctx.quadraticCurveTo(x+3,ym,x+10,yt)}ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}";
async function patchedIndex(){const r=await fetch('./index.html',{cache:'no-store'});let t=await r.text();t=t.replace(OLD1,NEW1).replace(OLD2,NEW2).replace(OLD3,NEW3);return new Response(t,{headers:{'Content-Type':'text/html; charset=utf-8'}})}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(ASSETS);await c.put('./index.html',await patchedIndex());self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin===location.origin&&(u.pathname.endsWith('/optical-ray-lab/')||u.pathname.endsWith('/optical-ray-lab/index.html'))){e.respondWith(caches.open(CACHE).then(c=>c.match('./index.html')).then(r=>r||patchedIndex()));return}e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}))) });